# Generated by Django 4.0.3 on 2022-04-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfb_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('drive_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('drive_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('home', models.CharField(blank=True, max_length=255, null=True)),
                ('away', models.CharField(blank=True, max_length=255, null=True)),
                ('week', models.PositiveIntegerField(blank=True, null=True)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('drive_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('play_number', models.PositiveIntegerField()),
                ('period', models.IntegerField(blank=True, null=True)),
                ('offense_score', models.IntegerField(blank=True, null=True)),
                ('defense_score', models.IntegerField(blank=True, null=True)),
                ('offense_timeouts', models.IntegerField(blank=True, null=True)),
                ('defense_timeouts', models.IntegerField(blank=True, null=True)),
                ('wallclock', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'play',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayDrive',
            fields=[
                ('i_d', models.BigAutoField(db_column='I_D', primary_key=True, serialize=False)),
                ('clock', models.CharField(blank=True, max_length=255, null=True)),
                ('yard_line', models.IntegerField(blank=True, null=True)),
                ('yards_to_goal', models.IntegerField(blank=True, null=True)),
                ('down', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('yards_gained', models.IntegerField(blank=True, null=True)),
                ('play_text', models.CharField(blank=True, max_length=800, null=True)),
                ('ppa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'play_drive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playtype',
            fields=[
                ('play_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('scoring', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'playtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamDefense',
            fields=[
                ('defense', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=255)),
                ('defense_conference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'team_defense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamOffense',
            fields=[
                ('offense', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=255)),
                ('offense_conference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'team_offense',
                'managed': False,
            },
        ),
    ]
