# Generated by Django 4.0.3 on 2022-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPlays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(blank=True, db_column='I_D', max_length=255, null=True)),
                ('drive_id', models.CharField(blank=True, max_length=255, null=True)),
                ('game_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_number', models.IntegerField(blank=True, null=True)),
                ('play_number', models.IntegerField(blank=True, null=True)),
                ('offense', models.CharField(blank=True, max_length=255, null=True)),
                ('offense_conference', models.CharField(blank=True, max_length=255, null=True)),
                ('offense_score', models.IntegerField(blank=True, null=True)),
                ('defense', models.CharField(blank=True, max_length=255, null=True)),
                ('home', models.CharField(blank=True, max_length=255, null=True)),
                ('away', models.CharField(blank=True, max_length=255, null=True)),
                ('defense_conference', models.CharField(blank=True, max_length=255, null=True)),
                ('defense_score', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('clock', models.CharField(blank=True, max_length=255, null=True)),
                ('offense_timeouts', models.IntegerField(blank=True, null=True)),
                ('defense_timeouts', models.IntegerField(blank=True, null=True)),
                ('yard_line', models.IntegerField(blank=True, null=True)),
                ('yards_to_goal', models.IntegerField(blank=True, null=True)),
                ('down', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.CharField(blank=True, max_length=255, null=True)),
                ('yards_gained', models.CharField(blank=True, max_length=255, null=True)),
                ('scoring', models.CharField(blank=True, max_length=255, null=True)),
                ('play_type', models.CharField(blank=True, max_length=255, null=True)),
                ('play_text', models.CharField(blank=True, max_length=800, null=True)),
                ('ppa', models.CharField(blank=True, max_length=255, null=True)),
                ('wallclock', models.CharField(blank=True, max_length=255, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'all_plays',
                'managed': False,
            },
        ),
    ]
